server.servlet.context-path=/common-library
spring.application.name=common-library
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://identity/realms/Yas
springdoc.oauthflow.authorization-url=http://identity/realms/Yas/protocol/openid-connect/auth
springdoc.oauthflow.token-url=http://identity/realms/Yas/protocol/openid-connect/token
cors.allowed-origins=*


# ===== TRACING (Tempo) =====
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://52.77.21.237:4318/v1/traces

# ===== LOGGING (Loki) =====
logging.level.com.yas=DEBUG

# ===== ACTUATOR =====
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.export.prometheus.enabled=true