#File này dùng để thiết lập một GitHub Action 
#để tự động kiểm tra xem mã nguồn có bị lộ các thông tin nhạy cảm hay không

name: GitLeaks check nightly

on:
  schedule:
    - cron: "0 0 * * *"  # Chạy vào đúng 00:00 mỗi ngày
  workflow_dispatch:      # Cho phép nhấn nút chạy thủ công khi cần

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Gitleaks check
        run: |
          docker pull zricethezav/gitleaks:v8.18.4
          docker run --rm -v ${{ github.workspace }}:/work -w /work zricethezav/gitleaks:v8.18.4 detect --source="." --config="/work/gitleaks.toml" --verbose
